#!/bin/bash

lid_status=`cat /proc/acpi/button/lid/LID/state | awk '{print $2}'`

vga_status=""
vga_status=`xrandr | grep ' connected ' | grep -A1 VGA1 | awk '{print $1}'`
hdmi_status=""
hdmi_status=`xrandr | grep ' connected ' | grep -A1 HDMI1 | awk '{print $1}'`

output_arg=""
position_arg=""

case "${1}" in
    set)
        if [ ! -z "$2" ]; then
            output_arg=$output_arg"--output ${2} --auto "
        fi

        if [ ! -z "$3" ]; then
            output_arg=$output_arg"--output ${3} --auto "
            position_arg=$position_arg"--output ${2} --left-of ${3} "
        fi

        if [ ! -z "$4" ]; then
            output_arg=$output_arg"--output ${4} --auto "
            position_arg=$position_arg"--output ${3} --left-of ${4} "
        fi
        ;;
    on)
        if [ ! -z "$2" ]; then
            output_arg=$output_arg"--output ${2} --auto"
        fi
        ;;
    off)
        if [ ! -z "$2" ]; then
            output_arg=$output_arg"--output ${2} --off"
        fi
        ;;
    auto)
        if [ "$lid_status"x == "open"x ]; then
            output_arg=$output_arg"--output eDP1 --auto "
        else
            output_arg=$output_arg"--output eDP1 --off "
        fi

        if [ ! -z "$hdmi_status" ]; then
            output_arg=$output_arg"--output HDMI1 --auto "
            if [ "$lid_status"x == "open"x ]; then
                position_arg=$position_arg"--output eDP1 --right-of HDMI1 "
            fi
        fi

        if [ ! -z "$vga_status" ]; then
            output_arg=${output_arg}"--output VGA1 --auto "
            if [ ! -z "$hdmi_status" ]; then
                position_arg=$position_arg"--output HDMI1 --right-of VGA1 "
            else
                position_arg=$position_arg"--output VGA1 --left-of eDP1 "
            fi
        fi
        ;;
    *)
        echo "error"
esac

if [ ! -z "$output_arg" ];then
    xrandr $output_arg$position_arg
else
    echo "You must input args."
fi

if [ ! -z "$hdmi_status" ]; then
    volume-tools switch hdmi
else
    volume-tools switch laptop
fi

change-wallpaper
