#!/bin/bash

mixer_control=`amixer | head -n 1 | sed "s/.*'\(.*\)'.*/\1/g"`

case "$1" in
    volume)
        volume_control="$2"
        amixer -q set $mixer_control $volume_control
        ;;
    num)
        if [ "$mixer_control" == "PCM" ]; then
            amixer | grep -A6 PCM | grep Left: | sed -rn 's/.*\[([0-9]+%)\].*/\1/p'
        fi
        if [ "$mixer_control" == "Master" ]; then
            amixer | grep -A10 'Master' | sed -rn 's/.*\[([0-9]+%)\].*/\1/p' | sed -n '1p'
        fi
        ;;
    switch)
        switch_to="$2"

        if [ "$switch_to" == "laptop" ]; then
            echo -e "defaults.pcm.card 1\ndefaults.pcm.device 0\ndefaults.ctl.card 1" > ~/.asoundrc
        fi

        if [ "$switch_to" == "hdmi" ]; then
            echo -e "defaults.pcm.card 0\ndefaults.pcm.device 3\ndefaults.ctl.card 0" > ~/.asoundrc
        fi
        ;;
    *)
        echo 'error'
        ;;
esac
